// Родовые слова, которые модели кладут в aliases; по ним объединять нельзя
const GENERIC_ALIASES = new Set(
  [
    "king",
    "queen",
    "prince",
    "princess",
    "lord",
    "lady",
    "sir",
    "master",
    "majesty",
    "your majesty",
    "highness",
    "father",
    "mother",
    "son",
    "daughter",
    "brother",
    "sister",
    "twin",
    "wife",
    "husband",
    "girl",
    "boy",
    "man",
    "woman",
    "old man",
    "old woman",
    "child",
    "knight",
    "young knight",
    "captain",
    "soldier",
    "guard",
    "baron",
    "count",
    "duke",
    "merchant",
    "innkeeper",
    "priest",
    "priestess",
    "bard",
    "poet",
    "wizard",
    "sorcerer",
    "sorceress",
    "witch",
    "witcher",
    "mage",
    "elf",
    "dwarf",
    "monster",
    "beast",
    "creature",
    "host",
    "stranger",
    "author",
    "narrator",
    "hero",
    "legendary hero",
    "король",
    "королева",
    "принц",
    "принцесса",
    "господин",
    "госпожа",
    "отец",
    "мать",
    "сын",
    "дочь",
    "брат",
    "сестра",
    "жена",
    "муж",
    "девушка",
    "парень",
    "мужчина",
    "женщина",
    "старик",
    "старуха",
    "ребёнок",
    "рыцарь",
    "капитан",
    "солдат",
    "стражник",
    "барон",
    "граф",
    "купец",
    "трактирщик",
    "жрец",
    "жрица",
    "бард",
    "поэт",
    "чародей",
    "чародейка",
    "ведьма",
    "ведьмак",
    "маг",
    "эльф",
    "краснолюд",
    "чудовище",
    "зверь",
    "существо",
    "хозяин",
    "незнакомец",
    "автор",
    "рассказчик",
    "герой",
  ].map((w) => w.toLowerCase()),
);

/** Похож ли алиас на имя собственное, а не на родовое описание («knight», «дочь»). */
export function looksLikeProperName(alias: string): boolean {
  const a = alias.trim();
  if (a.length < 3) return false;
  const base = a.replace(/^(the|a|an)\s+/i, "");
  if (GENERIC_ALIASES.has(base.toLowerCase())) return false;
  // Имя собственное начинается с заглавной буквы (латиница или кириллица)
  return /^[A-ZА-ЯЁ]/.test(base);
}

/** Тексты-заглушки, которые анализатор ставит вместо отсутствующих данных. */
const EMPTY_MARKERS = [
  "информация в тексте отсутствует",
  "not described in the text",
];

/** Возвращает null для пустых значений и заглушек анализатора. */
export function nonEmptyText(value: string | null | undefined): string | null {
  const trimmed = value?.trim() ?? "";
  if (!trimmed) return null;
  return EMPTY_MARKERS.includes(trimmed.toLowerCase()) ? null : trimmed;
}
