import Link from "next/link"
import { Search } from "lucide-react"
import { getGalleryImages } from "@/lib/actions/gallery"
import { GalleryCard } from "@/components/gallery-card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export default async function GalleryPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; page?: string }>
}) {
  const { q, page } = await searchParams
  const currentPage = page ? parseInt(page, 10) : 1
  
  const { images, total, totalPages } = await getGalleryImages({ 
    query: q, 
    page: currentPage 
  })

  return (
    <div className="container py-8 max-w-6xl mx-auto space-y-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Image Gallery</h1>
          <p className="text-muted-foreground">
            Explore images generated by our community.
          </p>
        </div>
        
        <form method="GET" action="/gallery" className="flex items-center gap-2 w-full md:w-auto">
          <div className="relative flex-1 md:w-80">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              type="search"
              name="q"
              placeholder="Search books or characters..."
              className="pl-8"
              defaultValue={q}
            />
          </div>
          <Button type="submit" variant="secondary">Search</Button>
          {q && (
            <Button variant="ghost" render={<Link href="/gallery" />}>
              Clear
            </Button>
          )}
        </form>
      </div>

      {images.length === 0 ? (
        <div className="text-center py-20 bg-muted/50 rounded-lg border border-dashed">
          <p className="text-muted-foreground">No images found.</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
            {images.map((image) => (
              <GalleryCard key={image.id} image={image} />
            ))}
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-4 pt-8">
              <Button
                variant="outline"
                disabled={currentPage <= 1}
                render={
                  <Link
                    href={`/gallery?${new URLSearchParams({
                      ...(q ? { q } : {}),
                      page: (currentPage - 1).toString(),
                    })}`}
                  />
                }
              >
                Previous
              </Button>
              <div className="text-sm text-muted-foreground">
                Page {currentPage} of {totalPages}
              </div>
              <Button
                variant="outline"
                disabled={currentPage >= totalPages}
                render={
                  <Link
                    href={`/gallery?${new URLSearchParams({
                      ...(q ? { q } : {}),
                      page: (currentPage + 1).toString(),
                    })}`}
                  />
                }
              >
                Next
              </Button>
            </div>
          )}
        </>
      )}
    </div>
  )
}
